# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asduser_data_lang_asduser_ui_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asduser',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
