# Generated by Django 4.2.3 on 2023-08-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'city',
                'ordering': ['etrap', 'name_0'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etrap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'etrap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=250, null=True)),
                ('name_1', models.CharField(blank=True, max_length=250, null=True)),
                ('name_2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_0', models.CharField(blank=True, max_length=250, null=True)),
                ('address_1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': True,
            },

        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sex',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Education_institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=250, null=True)),
                ('name_1', models.CharField(blank=True, max_length=250, null=True)),
                ('name_2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_0', models.CharField(blank=True, max_length=250, null=True)),
                ('address_1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.city')),
            ],
            options={
                'db_table': 'education_institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.hospital')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.sex')),
            ],
            options={
                'db_table': 'doctor',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='etrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.etrap'),
        ),
    ]
