# Generated by Django 4.2.3 on 2023-08-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='relation_hospital_city', to='dicts.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education_institution',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_education_institution_city', to='dicts.city'),
        ),
    ]
