# Generated by Django 4.2.3 on 2023-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0003_remove_doctor_first_name_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=150, null=True)),
                ('name_1', models.CharField(blank=True, max_length=150, null=True)),
                ('name_2', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
