# Generated by Django 4.2.3 on 2023-08-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0004_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_institution',
            name='etrap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relation_education_institution_etrap', to='dicts.etrap'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='etrap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relation_hospital_etrap', to='dicts.etrap'),
        ),
    ]
