# Generated by Django 4.2.3 on 2023-08-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0005_education_institution_etrap_hospital_etrap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'ordering': ['etrap', 'name_0'], 'verbose_name': 'Город/этрап', 'verbose_name_plural': 'Города/этрапы'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True, 'ordering': ['fullname_0'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='education_institution',
            options={'managed': True, 'ordering': ['name_0'], 'verbose_name': 'Учебное заведение', 'verbose_name_plural': 'Учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='etrap',
            options={'managed': True, 'ordering': ['name_0'], 'verbose_name': 'Велаят/город', 'verbose_name_plural': 'Велаяты/города'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': True, 'ordering': ['name_0'], 'verbose_name': 'Больница', 'verbose_name_plural': 'Больницы'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'managed': True, 'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': True, 'ordering': ['name_0'], 'verbose_name': 'Ед. измерения', 'verbose_name_plural': 'Ед. измерения'},
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
