# Generated by Django 4.2.3 on 2023-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0006_alter_city_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('name_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Типы операций',
                'verbose_name_plural': 'Тип операции',
                'db_table': 'surgery_type',
                'ordering': ['name_0'],
                'managed': True,
            },
        ),
    ]
