# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_options'),
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsurgery',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='diagnosis_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='diagnosis_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='diagnosis_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_patient_patient', to='patients.patient'),
        ),
    ]
