# Generated by Django 4.2.3 on 2023-08-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_0', models.CharField(blank=True, max_length=150, null=True)),
                ('name_1', models.CharField(blank=True, max_length=150, null=True)),
                ('name_2', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_0', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_1', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_2', models.CharField(blank=True, max_length=150, null=True)),
                ('child_count', models.IntegerField()),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('investment_name_0', models.CharField(blank=True, max_length=150, null=True)),
                ('investment_name_1', models.CharField(blank=True, max_length=150, null=True)),
                ('investment_name_2', models.CharField(blank=True, max_length=150, null=True)),
                ('count', models.DecimalField(decimal_places=2, max_digits=19)),
                ('price_man', models.DecimalField(decimal_places=2, max_digits=19)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='investor_investment_organization', to='investment.organization')),
                ('source', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='source_investment_organization', to='investment.organization')),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='investment_unit', to='dicts.unit')),
            ],
        ),
    ]
