# Generated by Django 4.2.3 on 2023-08-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='investment',
            table='investment',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizarion',
        ),
    ]
