# Generated by Django 4.2.3 on 2023-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_investment_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='price_man',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='investment',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
