# Generated by Django 4.2.3 on 2023-08-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_price_man_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investor_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='investor_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='investor_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor_investment_organization', to='investment.organization'),
        ),
    ]
