# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_investment_investor_0_investment_investor_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Использование средств', 'verbose_name_plural': 'Использование средств'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True, 'ordering': ['name_0'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
