# Generated by Django 4.2.3 on 2023-08-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_etrap'),
        ('dicts', '0005_education_institution_etrap_hospital_etrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name_0', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name_1', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=150, null=True)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('income_date', models.DateField(blank=True, null=True)),
                ('resolution_name_0', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution_name_1', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution_name_2', models.CharField(blank=True, max_length=150, null=True)),
                ('resolution_number', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('birth_certificate_date', models.DateField(blank=True, null=True)),
                ('additional_info_0', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info_1', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info_2', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution_patient_patient', to='patients.patient')),
                ('sex', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolution_patient_sex', to='dicts.sex')),
            ],
            options={
                'db_table': 'patient_resolution',
                'managed': True,
            },
        ),
    ]
