# Generated by Django 4.2.3 on 2023-08-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientresolution',
            old_name='last_name_0',
            new_name='lastname_0',
        ),
        migrations.RenameField(
            model_name='patientresolution',
            old_name='last_name_1',
            new_name='lastname_1',
        ),
        migrations.RenameField(
            model_name='patientresolution',
            old_name='last_name_2',
            new_name='lastname_2',
        ),
    ]
