# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0002_rename_last_name_0_patientresolution_lastname_0_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientresolution',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Решение', 'verbose_name_plural': 'Решения'},
        ),
    ]
