# Generated by Django 4.2.3 on 2023-08-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_0', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_0', models.CharField(blank=True, max_length=250, null=True)),
                ('comment_1', models.CharField(blank=True, max_length=250, null=True)),
                ('comment_2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_0', models.CharField(blank=True, max_length=250, null=True)),
                ('address_1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_2', models.CharField(blank=True, max_length=250, null=True)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.city')),
                ('education_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                            to='dicts.education_institution',
                                                            related_name='relation_patient_city')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.sex')),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
