# Generated by Django 4.2.3 on 2023-08-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_hospital_city_alter_education_institution_city'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='relation_patient_city', to='dicts.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education_institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dicts.education_institution'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dicts.sex'),
        ),
    ]
