# Generated by Django 4.2.3 on 2023-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name_2',
        ),
        migrations.AddField(
            model_name='patient',
            name='fullname_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fullname_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fullname_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
