# Generated by Django 4.2.3 on 2023-08-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0004_unit'),
        ('patients', '0004_remove_patient_first_name_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='etrap',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relation_patient_etrap', to='dicts.etrap'),
        ),
    ]
