# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_etrap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
    ]
