# Generated by Django 4.2.3 on 2023-08-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_remove_patient_first_name_0_and_more'),
        ('dicts', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_0', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_1', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_2', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_description_0', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnosis_description_1', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnosis_description_2', models.CharField(blank=True, max_length=500, null=True)),
                ('income_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('doctor_diagnosis_0', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_diagnosis_1', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_diagnosis_2', models.CharField(blank=True, max_length=150, null=True)),
                ('price_man', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('additional_info_0', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info_1', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info_2', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_hospital', to='dicts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_patient', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_diagnosis',
                'managed': True,
            },
        ),
    ]
