# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdiagnosis',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Диагноз', 'verbose_name_plural': 'Записи диагностики'},
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='diagnosis_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='diagnosis_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='diagnosis_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
