# Generated by Django 4.2.3 on 2023-08-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0002_hospital_city_alter_education_institution_city'),
        ('patients', '0003_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTherapy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_0', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_1', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_2', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_measure_0', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_measure_1', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_measure_2', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('diagnosis_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('income_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('therapy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('therapy_description', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnosis_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.doctor')),
                ('diagnosis_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
            options={
                'db_table': 'patient_therapy',
                'managed': True,
            },
        ),
    ]
