# Generated by Django 4.2.3 on 2023-08-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_hospital_city_alter_education_institution_city'),
        ('therapy', '0002_patienttherapy_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttherapy',
            old_name='diagnosis_price',
            new_name='price_man',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_date',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_doctor',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_hospital',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_measure_0',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_measure_1',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='diagnosis_measure_2',
        ),
        migrations.RemoveField(
            model_name='patienttherapy',
            name='therapy_price',
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='therapy_doctor', to='dicts.doctor'),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='therapy_hospital', to='dicts.hospital'),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='therapy_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
