# Generated by Django 4.2.3 on 2023-08-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_rename_diagnosis_price_patienttherapy_price_man_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttherapy',
            old_name='additional_info',
            new_name='additional_info_0',
        ),
        migrations.RenameField(
            model_name='patienttherapy',
            old_name='therapy_description',
            new_name='therapy_description_0',
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='additional_info_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='additional_info_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='therapy_description_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='therapy_description_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
