# Generated by Django 4.2.3 on 2023-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_rename_additional_info_patienttherapy_additional_info_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttherapy',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='doctor_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='doctor_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='doctor_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
