# Generated by Django 4.2.3 on 2023-08-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_options'),
        ('therapy', '0005_remove_patienttherapy_doctor_patienttherapy_doctor_0_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienttherapy',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Лечение', 'verbose_name_plural': 'Записи о лечении'},
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='diagnosis_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='diagnosis_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='diagnosis_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapy_patient', to='patients.patient'),
        ),
    ]
