# Generated by Django 4.2.3 on 2023-09-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0007_surgerytype'),
        ('therapy', '0006_alter_patienttherapy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttherapy',
            name='hospital_therapy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_therapy_hospital', to='dicts.hospital'),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='hospital',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapy_hospital', to='dicts.hospital'),
        ),
    ]
