# Generated by Django 4.2.3 on 2023-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0007_patienttherapy_hospital_therapy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttherapy',
            name='department_therapy_0',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='department_therapy_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='department_therapy_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='additional_info_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='additional_info_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='additional_info_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='therapy_description_0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='therapy_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttherapy',
            name='therapy_description_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
